---
vagrant:
  hosts:
    192.168.33.10:
      ansible_ssh_private_key_file: .vagrant/machines/server/libvirt/private_key
    192.168.33.11:
      ansible_ssh_private_key_file: .vagrant/machines/user/libvirt/private_key
  vars:
    ansible_ssh_user: vagrant

server:
  hosts:
    192.168.1.100:
      ansible_ssh_user: home
      ansible_ssh_private_key_file: .no_file
