---

- hosts: vagrant
  become: true
  tasks:
  - name: change DNF settings (fastestmirror)
    community.general.ini_file:
      path: /etc/dnf/dnf.conf
      section: main
      option: fastestmirror
      value: 1
      state: present
      no_extra_spaces: yes
  - name: change DNF settings (max_parallel_downloads)
    community.general.ini_file:
      path: /etc/dnf/dnf.conf
      section: main
      option: max_parallel_downloads
      value: 20
      state: present
      no_extra_spaces: yes
  - name: change Fedora repo mirror
    community.general.ini_file:
      path: /etc/yum.repos.d/fedora.repo
      section: fedora
      option: baseurl
      value: https://free.nchc.org.tw/fedora/linux/releases/$releasever/Everything/$basearch/os/
      state: present
      no_extra_spaces: yes
  - name: change Fedora Updates repo mirror
    community.general.ini_file:
      path: /etc/yum.repos.d/fedora-updates.repo
      section: updates
      option: baseurl
      value: https://free.nchc.org.tw/fedora/linux/updates/$releasever/Everything/$basearch/
      state: present
      no_extra_spaces: yes
  - name: change Fedora Modular repo mirror
    community.general.ini_file:
      path: /etc/yum.repos.d/fedora-modular.repo
      section: fedora-modular
      option: baseurl
      value: https://free.nchc.org.tw/fedora/linux/releases/$releasever/Modular/$basearch/os/
      state: present
      no_extra_spaces: yes
  - name: change Fedora Modular Updates repo mirror
    community.general.ini_file:
      path: /etc/yum.repos.d/fedora-updates-modular.repo
      section: updates-modular
      option: baseurl
      value: https://free.nchc.org.tw/fedora/linux/updates/$releasever/Modular/$basearch/
      state: present
      no_extra_spaces: yes
  - name: Enable RPM Fusion repo
    dnf:
      name: 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-35.noarch.rpm'
      state: present
      disable_gpg_check: yes
  - name: change RPM Fusion Free repo mirror
    community.general.ini_file:
      path: /etc/yum.repos.d/rpmfusion-free.repo
      section: rpmfusion-free
      option: baseurl
      value: https://free.nchc.org.tw/rpmfusion/free/fedora/releases/$releasever/Everything/$basearch/os/
      state: present
      no_extra_spaces: yes
  - name: change RPM Fusion Free Updates repo mirror
    community.general.ini_file:
      path: /etc/yum.repos.d/rpmfusion-free-updates.repo
      section: rpmfusion-free-updates
      option: baseurl
      value: https://free.nchc.org.tw/rpmfusion/free/fedora/updates/$releasever/$basearch/
      state: present
      no_extra_spaces: yes

- hosts: 192.168.33.11
  become: true
  tasks:
  - name: Install Xfce4
    dnf:
      name: '@Xfce'
      state: present

